### ISSUE TITLE
大佬，试过父子项目用platform么

### ISSUE THREAD

**Issue by prlei** [techstay/java-learn#1]
希望花点时间出个父子、多模块的gradle小教程，感激不尽

**Comment by techstay** [comment]
父子多模块的好弄，这个platform是啥我还没真听说过……

**Comment by prlei** [comment]
platform 是spring官方出的整合一套版本的工具啊，比如platform某个版本，对应 commons-lang3 的3.3.2版本等等。

**Comment by techstay** [comment]
哦，你说那个啊，我也稍微了解过一下，不过你说这个platform、父子多模块的gradle，我还是有点不清楚，你再详细说说具体点的，我看看怎么简单弄个小例子

**Comment by techstay** [comment]
我传了一个例子，你看看咋样
